export const groupedFacilities = {
    'MARKED ROUTES': 'Marked Routes',
    'MARKED ROUTE': 'Marked Routes',
    'EXISTING SHARED LANE MARKINGS': 'Shared Lane Markings',
    'SHARED LANE MARKINGS': 'Shared Lane Markings',
    'CLIMBING LANES': 'Climbing Lanes',
    'EXISTING CLIMBING LANES': 'Climbing Lanes',
    'EXISTING PAVED SHOULDER': 'Paved Shoulder',
    'EXISTING BIKE LANES': 'Bike Lanes',
    'BIKE LANES': 'Bike Lanes',
    'EXISTING PROTECTED BIKE LANES': 'Protected Bike Lanes',
    'EXISTING BUFFERED BIKE LANES': 'Buffered Bike Lanes',
    'BUFFERED BIKE LANES': 'Buffered Bike Lanes',
    'EXISTING BIKE BOULEVARD': 'Bike Boulevard',
    'BIKE BOULEVARD': 'Bike Boulevard',
    'EXISTING CYCLE TRACK': 'Cycle Track',
    'OFF-STREET CONNECTION': 'Trail',
    'EXISTING TRAIL': 'Trail',
    'FURTHER STUDY NEEDED': 'Ignore',
    'NOT PART OF BMP': 'Ignore',
}